apiVersion: backstage.io/v1beta2
kind: Template
metadata:
  name: redocly-template
  title: Starter For Redocly  
  description: Starter For Redocly
spec:
  owner: zemoso/ashish-das
  type: service
  parameters:
    - title: Please fill the below
      required:
        - name
        - owner
      properties:
        name:
        title: Name
        type: string
        description: Unique name of the component
        ui:autofocus: true
        description:
        title: Description
        type: string
        description: Help others understand what this app does.
        owner:
        title: Owner
        type: string
        description: Owner of the component
        ui:field: OwnerPicker
        ui:options:
        allowedKinds:
        - Group
    - title: Choose Location
      required:
        - repoUrl
      properties:
        repoUrl:
        title: Repository Location
        type: string
        ui:field: RepoUrlPicker
        ui:options:
        allowedHosts:
        - github.com
steps:
  - id: fetch
    name: Fetching Code
    actions: fetch:template
    input:
      url: https://github.com/das-ashish/redocly-template
      values:
      name: "{{ parameters.name }}"
      owner: "{{parameters.owner}}"
      copyWithoutRender:
      - "*.html"
      - "*.js"
      - "*.tsx"
      - "*.ts"
      - "*.github"
    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ["github.com"]
        description: "This is {{ parameters.name }}"
        repoUrl: "{{ parameters.repoUrl }}"
  - id: register
    name: Register
    action: catalog:register
    input:
      repoContentsUrl: "{{ steps.publish.output.repoContentsUrl }}"
      catalogInfoPath: "/catalog-info.yaml"